### PR TITLE
changed styling of suggestions container to scroll and made the input…

### PR DESCRIPTION
**Pull request by Rangoons**
… sticky

### CODE REVIEW

**Comment by Miodec** [comment]
The suggestions box still gets cut off in the screen is very, very small. You can scroll with the mouse, but when using arrow keys to make a selection, the suggestions box does not scroll

**Comment by Rangoons** [comment]
@Miodec what is the smallest resolution you want to support?

**Comment by Miodec** [comment]
I mean, ideally as much as we can. I think its getting cut off because the height is measured in vh but its distance from the top is static, measured in rem.

**Comment by Rangoons** [comment]
changing the vh to 60 works a bit better on the smaller screen size. I'll have to investigate the arrow key scrolling. I'm going to guess its because the event is being repurposed to switch the highlighted item. I'll mess around with it this weekend

**Comment by Miodec** [comment]
Any update on this?

**Comment by Miodec** [comment]
Already implemented

**Pull request closed without merging**
