### PR TITLE
use rounded accuracy in post-game summary

### PR DESCRIPTION
**Pull request by g-harel**

### CODE REVIEW

**Comment by g-harel** [comment]
Now that I think of it, it would probably be better to only show 100 if there are no errors. I can make that a special case, but I'd like to test that more thoroughly tonight.

**Comment by Miodec** [comment]
Thats why the accuracy is floored and not rounded

**Comment by g-harel** [comment]
So what do you think, is this worth changing? Most other metrics are rounded so it was a little surprising, but I can see the logic.

**Comment by Miodec** [comment]
Yeah i would just leave it as it is.

**Pull request closed without merging**
